kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: rm343712-hpa
  namespace: gustavonj-dev
  uid: c0bfbd04-7a29-48a8-a785-b4dd53f7ef1b
  resourceVersion: '1320954037'
  creationTimestamp: '2022-07-15T20:42:32Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2beta2
      time: '2022-07-15T20:42:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v2
      time: '2022-07-15T20:43:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"AbleToScale"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingActive"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingLimited"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:currentMetrics': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
          'f:lastScaleTime': {}
      subresource: status
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: rm343712-app
    apiVersion: apps.openshift.io/v1
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
status:
  lastScaleTime: '2022-07-15T20:42:47Z'
  currentReplicas: 3
  desiredReplicas: 3
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: 1m
          averageUtilization: 16
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-07-15T20:42:47Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-07-15T20:43:02Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2022-07-15T20:48:33Z'
      reason: TooFewReplicas
      message: the desired replica count is less than the minimum replica count
